### ISSUE TITLE
Problems with Concepticon mapping

### ISSUE THREAD

**Issue by FredericBlum** [lexibank/zhangrgyalrong#9]
@LinguList  Since it seems that I am not allowed to create a new branch in this repository, I'll create an issue instead of a PR. The `lexibank`-script needs an addtion of the following two lines around line 63:

```
                    Concepticon_ID=concept.concepticon_id,
                    Concepticon_Gloss=concept.concepticon_gloss,
```

In it's current state, the concept list gets loaded, but the Glosses and ID are not added to the CLDF set, hence they are lacking from the final dataset.

**Comment by FredericBlum** [comment]
`remote: Permission to lexibank/zhangrgyalrong.git denied to FredericBlum.`

**Comment by LinguList** [comment]
Thanks, @FredericBlum. This particular dataset is a dataset I would not add to lexibank, however, since it contains, if you check the data, etymologigal data and concepts are linked to concepticon, but only for the root. 

However, the much bigger dataset `lexibank/lairgyalrong` contains Rgyalrongic data for about 300 concepts per variety, so this is giving us some additional coverage for this subgroup.

**Comment by FredericBlum** [comment]
Thanks for the tip, I have removed zhangrgyalrong and added lairgyalrong to the lexibank-sheet accordingly.
